create:
	conda env create -f requirements.yml python=3.8
	conda activate lidar_pac
	python install_torch.py
create_with_CUDA:
        conda env create -f requirements.yml python=3.8
        conda activate lidar_pac_with_GPU
        python install_torch.py
activate:
	conda activate lidar_pac2
